export const ADD_COMPLAINT_REQUEST = "ADD_COMPLAINT_REQUEST";
export const ADD_COMPLAINT_SUCCESS = "ADD_COMPLAINT_SUCCESS";
export const ADD_COMPLAINT_FAILED = "ADD_COMPLAINT_FAILED";

export const DELETE_COMPLAINT_SUCCESS = "DELETE_COMPLAINT_SUCCESS";
export const DELETE_COMPLAINT_FAILED = "DELETE_COMPLAINT_FAILED";
export const DELETE_COMPLAINT_REQUEST = "DELETE_COMPLAINT_REQUEST";

export const GET_COMPLAINT_FAILED = "GET_COMPLAINT_FAILED";
export const GET_COMPLAINT_REQUEST = "GET_COMPLAINT_REQUEST";
export const GET_COMPLAINT_SUCCESS = "GET_COMPLAINT_SUCCESS";

export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAILED = "UPLOAD_FAILED";
