export const ADD_COMPLAINT_REQUEST = "ADD_COMPLAINT_REQUEST";
export const ADD_COMPLAINT_SUCCESS = "ADD_COMPLAINT_SUCCESS";
export const ADD_COMPLAINT_FAILED = "ADD_COMPLAINT_FAILED";

export const REMOVE_COMPLAINT_SUCCESS = "REMOVE_COMPLAINT_SUCCESS";
export const REMOVE_COMPLAINT_FAILED = "REMOVE_COMPLAINT_FAILED";

export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAILED = "UPLOAD_FAILED";
